



"""
mainMenu
send_name_and_surname
send_number_register
send_number_register_button
name_error
select_filial
successfully_registered
filial_not_found
contact_with_phone
our_addresses
address_not_found
support
offers
support_accepted
no_orders
my_orders_order_text_one_line
product_added_to_busket
cart_empty
nothing_in_busket
send_location
send_location_button
skip_location
send_your_self_image
send_your_self_image
send_your_password_iamge
send_your_self_and_passport_image
is_your_number
yes
no
your_order_accepted
send_number_as_text
your_order_accepted
send_your_self_image_error
send_your_passport_image_error
send_your_self_password_image_error
settings_info
enter_new_name
name_changed
settings_name_error
select_new_language
language_changed
language_not_found
enter_new_number
send_number_button
number_changed
settings_number_error
select_new_filial
filial_changed
filial_not_found
back
month
per_month








"""