# Generated by Django 4.0.3 on 2022-04-22 17:19

import admin_panel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=15)),
                ('name_ru', models.CharField(max_length=15)),
                ('mode', models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'video')])),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('caption', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(models.Model, admin_panel.models.Name),
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Busket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('self_image', models.ImageField(blank=True, null=True, upload_to='busket')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='busket')),
                ('self_password_image', models.ImageField(blank=True, null=True, upload_to='busket')),
                ('extra_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('base_percent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fillials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name_uz', models.CharField(max_length=200)),
                ('_name_ru', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.fillials')),
                ('language', models.ForeignKey(on_delete=models.SET(1), to='admin_panel.language')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.language')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
                ('active', models.BooleanField(default=False)),
                ('tan_price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.color')),
            ],
        ),
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.color')),
            ],
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(default='/static/dashboard/assets/img/default.png', upload_to='images/')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('is_have', models.BooleanField(default=False)),
                ('pers', multiselectfield.db.fields.MultiSelectField(choices=[('order', 'Buyurtmalar'), ('statistic', 'Statistika'), ('operators', 'Operatorlar'), ('category', 'Kategoriya'), ('Ad', 'Рассылки'), ('fillial', 'Filliallar'), ('settings', 'Bot Sozlamalari'), ('followers', 'Foydalanuvchilar')], max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user')),
            ],
        ),
        migrations.CreateModel(
            name='BusketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_count', models.IntegerField()),
                ('busket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.busket')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.percent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product')),
            ],
        ),
        migrations.AddField(
            model_name='busket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='admin_panel.location'),
        ),
        migrations.AddField(
            model_name='busket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user'),
        ),
    ]
