# Generated by Django 4.0.3 on 2022-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
