# Generated by Django 4.0.3 on 2022-04-22 19:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillials',
            old_name='_name_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='fillials',
            old_name='_name_uz',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='fillials',
            name='_desc_ru',
            field=ckeditor.fields.RichTextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fillials',
            name='_desc_uz',
            field=ckeditor.fields.RichTextField(default='1'),
            preserve_default=False,
        ),
    ]
