# Generated by Django 4.0.3 on 2022-04-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busket',
            old_name='is_ordered',
            new_name='bis_ordered',
        ),
    ]
