# Generated by Django 4.0.3 on 2022-05-13 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'jpg', 'png', 'mow', 'avi', '3gp', 'gif'])]),
        ),
    ]
