# Generated by Django 4.0.3 on 2022-04-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_rename__name_ru_fillials_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillials',
            old_name='_desc_ru',
            new_name='desc_ru_f',
        ),
        migrations.RenameField(
            model_name='fillials',
            old_name='_desc_uz',
            new_name='desc_uz_f',
        ),
    ]
