# Generated by Django 4.0.3 on 2022-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_ads_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='mode',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'video')], default=0),
        ),
    ]
