# Generated by Django 4.0.3 on 2022-05-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_botsettings_request_passport_image_and_more'),
        ('admin_panel', '0002_product_desc_ru_product_desc_uz'),
    ]

    operations = [
    ]
