# Generated by Django 4.0.3 on 2022-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_fillials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
