# Generated by Django 4.0.3 on 2022-04-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_ads'),
        ('admin_panel', '0002_rename_is_ordered_busket_bis_ordered'),
    ]

    operations = [
    ]
