# Generated by Django 4.0.3 on 2022-04-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0003_busket_actioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket',
            name='actioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioner', to=settings.AUTH_USER_MODEL),
        ),
    ]
