# Generated by Django 4.0.3 on 2022-04-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_merge_20220425_2003'),
        ('admin_panel', '0003_merge_20220425_2006'),
    ]

    operations = [
    ]
