# Generated by Django 4.0.3 on 2022-04-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename__desc_ru_fillials_desc_ru_f_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillials',
            name='desc_ru_f',
        ),
        migrations.RemoveField(
            model_name='fillials',
            name='desc_uz_f',
        ),
    ]
