# Generated by Django 4.0.3 on 2022-04-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_operators_pers'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
