# Generated by Django 4.0.3 on 2022-05-10 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_merge_20220505_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='answer',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busket',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/busket'),
        ),
        migrations.AlterField(
            model_name='busket',
            name='self_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/busket'),
        ),
        migrations.AlterField(
            model_name='busket',
            name='self_password_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/busket'),
        ),
    ]
