# Generated by Django 3.2.9 on 2022-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_botsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
