# Generated by Django 4.0.3 on 2022-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_ads_created_at_aksiya_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksiya',
            name='mode',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'video')], default=0),
        ),
    ]
