# Generated by Django 4.0.3 on 2022-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_busket_actioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
