# Generated by Django 4.0.3 on 2022-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_aksiya_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='password',
            field=models.CharField(default='sdf', max_length=999999),
            preserve_default=False,
        ),
    ]
