# Generated by Django 4.0.3 on 2022-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_operators_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='surname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
