# Generated by Django 4.0.3 on 2022-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_fillials_desc_ru_fillials_desc_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilindi'), (2, 'Rad etildi'), (3, 'Tasdiqlandi'), (4, 'Tasdiqlanmadi'), (5, 'Arxiv')], default=0),
            preserve_default=False,
        ),
    ]
