# Generated by Django 3.2.9 on 2022-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20220402_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='photo',
            field=models.ImageField(default='/static/dashboard/assets/img/default.png', upload_to='images/'),
        ),
    ]
