# Generated by Django 4.0.3 on 2022-06-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_operators_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operators',
            old_name='password',
            new_name='password2',
        ),
    ]
