# Generated by Django 4.0.3 on 2022-04-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_operators_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='operators',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
