# Generated by Django 4.0.3 on 2022-04-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_operators_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Kutilmoqda'), (1, 'Qabul qilindi'), (2, 'Rad etildi'), (3, 'Tasdiqlandi!'), (4, 'Tasdiqlanmadi'), (5, 'Arxiv')], default=0),
        ),
    ]
