# Generated by Django 4.0.3 on 2022-06-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_rename_password_operators_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='photo',
            field=models.ImageField(blank=True, default='/static/dashboard/assets/img/default.png', null=True, upload_to='images/'),
        ),
    ]
