# Generated by Django 4.0.3 on 2022-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_busket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
