# Generated by Django 4.0.3 on 2022-04-02 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_operators_address_operators_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillials',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='fillials',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fillials',
            name='desc_uz',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fillials',
            name='name_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
