# Generated by Django 4.0.3 on 2022-04-24 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_busket_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket',
            name='actioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioner', to='admin_panel.operators'),
        ),
    ]
