# Generated by Django 4.0.3 on 2022-06-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_support_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='media_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'video')], default=0),
        ),
    ]
