# Generated by Django 4.0.3 on 2022-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_category_color_product_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='is_have',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
