# Generated by Django 4.0.3 on 2022-04-25 15:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='pers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('statistic', 'Statistika'), ('operators', 'Operatorlar'), ('category', 'Kategoriya'), ('ads', 'Reklama'), ('fillial', 'Filliallar'), ('present', 'Aksiyalar'), ('settings', 'Bot Sozlamalari'), ('text', 'Textlar'), ('followers', 'Foydalanuvchilar')], max_length=72),
        ),
    ]
