# Generated by Django 4.0.3 on 2022-04-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_language_user_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='xxx', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.language')),
            ],
        ),
    ]
