# Generated by Django 4.0.3 on 2022-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_remove_category_name_ru_remove_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default='f', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category_name',
        ),
    ]
