# Generated by Django 4.0.3 on 2022-04-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_busket_busketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='percent',
            name='months',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tan_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='percent',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
