# Generated by Django 4.0.3 on 2022-04-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_percent_months_product_tan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busketitem',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.percent'),
            preserve_default=False,
        ),
    ]
