# Generated by Django 4.0.3 on 2022-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_busketitem_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
