# Generated by Django 4.0.3 on 2022-04-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_busket_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='extra_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='busket',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='busket'),
        ),
        migrations.AddField(
            model_name='busket',
            name='self_image',
            field=models.ImageField(blank=True, null=True, upload_to='busket'),
        ),
        migrations.AddField(
            model_name='busket',
            name='self_password_image',
            field=models.ImageField(blank=True, null=True, upload_to='busket'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user')),
            ],
        ),
        migrations.AddField(
            model_name='busket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='admin_panel.location'),
        ),
    ]
