# Generated by Django 4.0.3 on 2022-04-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0020_busket_extra_number_busket_passport_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operators',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operators',
            name='password',
        ),
        migrations.RemoveField(
            model_name='operators',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='operators',
            name='username',
        ),
        migrations.AddField(
            model_name='operators',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
