# Generated by Django 4.0.3 on 2022-04-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_busket_extra_number_busket_passport_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.fillials'),
        ),
    ]
