# Generated by Django 4.0.3 on 2022-04-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_remove_operators_name_remove_operators_password_and_more'),
        ('admin_panel', '0021_user_filial'),
    ]

    operations = [
    ]
