# Generated by Django 4.0.3 on 2022-04-20 18:32

import admin_panel.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_merge_20220419_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=15)),
                ('name_ru', models.CharField(max_length=15)),
                ('mode', models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'video')])),
                ('media', models.FileField(upload_to='')),
                ('caption', models.TextField(validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'mp4', 'avi', 'mov'])])),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(models.Model, admin_panel.models.Name),
        ),
    ]
