# Generated by Django 4.0.3 on 2022-04-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_aksiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksiya',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
