# Generated by Django 4.0.3 on 2022-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_aksiya_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksiya',
            name='caption',
            field=models.TextField(),
        ),
    ]
