# Generated by Django 4.0.3 on 2022-04-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_alter_operators_pers'),
        ('admin_panel', '0025_alter_aksiya_caption'),
    ]

    operations = [
    ]
