# Generated by Django 4.0.3 on 2022-04-21 22:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_merge_20220421_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='pers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'Asosiy'), ('order', 'Buyurtmalar'), ('statistic', 'Statistika'), ('operators', 'Operatorlar'), ('category', 'Kategoriya'), ('ads', 'Reklama'), ('fillial', 'Filliallar'), ('settings', 'Bot Sozlamalari'), ('followers', 'Foydalanuvchilar')], max_length=70),
        ),
    ]
