# Generated by Django 4.0.3 on 2022-04-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_alter_operators_pers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operators',
            name='token',
        ),
    ]
