

# TOKEN = "1506972284:AAGz_yT8Aj-JBdUt8K9ThsDmeDivec3_-Ec"
TOKEN = "1506972284:AAGP5pUyFdAsOzkb9A5B43BwanqmZcaY9nI"


LANGUAGE, NAME, NUMBER, FILIAL, MENU, ORDER, CART_ORDER_LOCATION, CART,CART_ORDER_SELF_IMAGE,CART_ORDER_PASSPORT_IMAGE, CART_ORDER_SELF_PASSWORD_IMAGE, CART_ORDER_CHECK_NUMBER, GET_NUMBER_FOR_ORDER, SETTINGS, SETTINGS_NAME, SETTINGS_LANGUAGE, SETTINGS_NUMBER, OUR_ADDRESSES, SUPPORT, ADDRESS, AKSIYA, MY_ORDERS, SETTINGS_FILIAL  = range(23)
