

TOKEN = "5042361530:AAH-nMQNo3B0hwvXuxJLa3rhCkNHhXYEY0Y"


LANGUAGE, NAME, NUMBER, MENU, ORDER, CART_ORDER_LOCATION, CART,CART_ORDER_SELF_IMAGE,CART_ORDER_PASSPORT_IMAGE, CART_ORDER_SELF_PASSWORD_IMAGE, CART_ORDER_CHECK_NUMBER, GET_NUMBER_FOR_ORDER  = range(12)